[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/go-resty/resty"
  version = "1.12.0"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "1.1.2"
